version: '3'
# list out mysql and node service
services:
  autoapp_mysql_comp:
    image: liamlows/autoapp_mysql
    build: ./BackEnd/MYSQL
    container_name: autoapp_mysql_comp
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql
  autoapp_node_comp:
    image: liamlows/autoapp_node-api
    build: ./BackEnd/NODE
    container_name: autoapp_node_comp
    restart: always
    ports:
      - 8080:8080
    links:
      - autoapp_mysql_comp:autoapp_mysql_comp
    depends_on:
      - autoapp_mysql_comp
    volumes:
      - ./BackEnd/NODE:/var/lib/node
  autoapp_nginx_comp:
    image: liamlows/autoapp_nginx
    build: ./FrontEnd
    container_name: autoapp_nginx_comp
    restart: always
    ports:
      -  80:80
    links:
      - autoapp_node_comp:autoapp_node_comp
    volumes:
      -  ./FrontEnd/car_app/build:/var/www

volumes:
  mysql_volume:
